# Generated by Django 5.2.7 on 2025-11-03 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('commerces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.order'),
        ),
        migrations.AddField(
            model_name='orderitemoption',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.orderitem'),
        ),
        migrations.AddField(
            model_name='orderpromo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.order'),
        ),
        migrations.AddField(
            model_name='orderpromo',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.promocode'),
        ),
        migrations.AlterUniqueTogether(
            name='orderpromo',
            unique_together={('order', 'promo_code')},
        ),
    ]
